### ISSUE TITLE
Starlabs theme (Light) - Invisible text

### ISSUE THREAD

**Issue by Stephen-StarLabs** [StarLabsLtd/StarLabsTheme#1]
Selected partition results in invisible text.

An example in GNOME Disks:

![image](https://user-images.githubusercontent.com/43813383/53016693-18cdb400-3446-11e9-8aeb-94bd9c584a8a.png)

![image](https://user-images.githubusercontent.com/43813383/53016727-24b97600-3446-11e9-8dd6-bbd0b11962dc.png)

**Comment by KushagraKarira** [comment]
similar problems in firefox-esr on debian.
