### ISSUE TITLE
After the recent update, StarLabs Darker color in terminal looks exactly like StarLabs Lighter. 

### ISSUE THREAD

**Issue by PranavBhattarai** [StarLabsLtd/StarLabsTheme#11]
This is the screenshot Star Lab Darker, which isn't darker anymore after recent changes.
![Screenshot from 2019-07-20 18-54-28](https://user-images.githubusercontent.com/32763112/61579073-0bfddb00-ab20-11e9-9f0a-973e8c297b82.png)

This is the screenshot of Star Lab Whiter, which is white. Does as its name suggest. 
![Screenshot from 2019-07-20 18-55-09](https://user-images.githubusercontent.com/32763112/61579094-6a2abe00-ab20-11e9-8053-0c983a971452.png)

This is bad. Why a fine Dark theme is suddenly made Blue in the terminal? People choose this shiny black theme for a reason. It consumes less battery and it goes easy on the eyes.

The blues color effect on the terminal is pointless. People in Linux use the terminal a lot. A am no different.

_Before I remove this theme, I had to express my feelings toward this issue. I will be missing u guys. Hope next update fix this if this is some of mistake.  _

**Comment by Sean-StarLabs** [comment]
Sorry to hear you don't like the update. It was intentional as most theme's do follow this trend.

That said, we are working on an update that should be available in a week or so, there will be several new variants such as green and red accent colours. One variant will be called OLED, which will use true black so anyone such as yourself, with an OLED display, can get the maximum power savings available.

**Comment by PranavBhattarai** [comment]
Is there a certain timeline. I will be happy to know...if there is a release date.

**Comment by Sean-StarLabs** [comment]
About a week :)

**Comment by Sean-StarLabs** [comment]
I've just uploaded a beta version which has the "colours" update in it. If you want to give it a try, it's either in GitHub under the `nextgen` branch or our beta PPA `starlabs/beta`.

We've still got a bit to do but it's mostly there.

**Comment by PranavBhattarai** [comment]
> I've just uploaded a beta version which has the "colours" update in it. If you want to give it a try, it's either in GitHub under the `nextgen` branch or our beta PPA `starlabs/beta`.
> 
> We've still got a bit to do but it's mostly there.

That good to know. But I will like to wait until its official.
_Beta can create annoying issues._

**Comment by Sean-StarLabs** [comment]
It's now stable. Available in GitHub and our PPA 😀
