### ISSUE TITLE
Alt+Ctrl+Tab creates 2 terminals

### ISSUE THREAD

**Issue by SamuelBailey** [StarLabsLtd/StarLabsTheme#14]
I have found on ubuntu 19.10, that when I have the starlabs theme installed there is a bug with the keyboard shortcut for spawning a terminal window Ctrl+Alt+T. If Ctrl and Alt are pressed the other way around (Alt+Ctrl+T), and the currently selected window is a terminal window, then 2 new terminal windows will be spawned instead of 1.

I believe that this is bug with the starlabs theme when being used with ubuntu 19.10. I first noticed it on a machine upon which I updated from 19.04 to 19.10. I never noticed this behaviour in ubuntu 19.04, but did after the upgrade. I have since done a fresh install of ubuntu 19.10 on a separate machine, and the behaviour was not present until after I installed the starlabs theme.

**Comment by Sean-StarLabs** [comment]
I'm not sure what your seeing but:
Gnome can't distinguish between Ctrl + Alt and Alt + Ctrl
Theme's don't affect keyboard shortcuts

The only thing I can think of is that it's either, a second shortcut for Alt + T or a specific shortcut on your keyboard.

If you let me know what you're running, I can look into it further.
