### ISSUE TITLE
Text contrast on out-of-focus tabs

### ISSUE THREAD

**Issue by th3bucch** [StarLabsLtd/StarLabsTheme#15]
Hi, 
after latest update via ppa, text of not active tabs in apps without menu-bar (i.e Firefox) is difficult to read. Doesn't have enough contrast.
I'm using StarLabs default theme (light and dark are working fine) on Ubuntu 18.04, Firefox 70.0.1.

The active tab is the one on the left, the right one is the one i'm referring to. Hardly readable when fullscreen or low brightness.
![ffx2](https://user-images.githubusercontent.com/57603626/68551853-32b68900-0411-11ea-9f86-25e342815eee.png)

Will it be fixed on a next release? If not, where i can change font color for those tabs on default theme?

Thanks

**Comment by Sean-StarLabs** [comment]
Seems your Firefox has the tabs and title bar merged together.

Mine and a fresh build look like this:
![image](https://user-images.githubusercontent.com/38053956/68583407-f0bf2e80-0474-11ea-9026-9e5a588e69df.png)

Are you using an extension or theme to do this?

**Comment by th3bucch** [comment]
No extensions or themes at all, it's just a firefox feature to maximize screen space. On windows it's like this by default.
You have to untick "title bar" at the bottom-left of Customize page.

**Comment by Sean-StarLabs** [comment]
Got it. Will fix now, thanks

**Comment by th3bucch** [comment]
Thank you for your good work!

**Comment by th3bucch** [comment]
Hi Sean, sorry to bother you again.
I just updated the theme via ppa and the tabs are darker than before. Now is completely unreadable.
Mind that my screenshot app slightly increase brightness of the image.

![DeepinScreenshot_seleziona-area_20191113201346](https://user-images.githubusercontent.com/57603626/68795894-22d9b780-0652-11ea-9b9f-70f36661ba1e.png)

Already logged out and on again to refresh theme.

**Comment by th3bucch** [comment]
> Second time lucky! Just set 1.0.5 building - it definitely works!
> 
> Thanks for your help with this :)

Yep, it's working properly now!
![DeepinScreenshot_seleziona-area_20191115180501](https://user-images.githubusercontent.com/57603626/68961371-8854b200-07d2-11ea-9a73-2088adc47f2f.png)

Thank you again!

**Comment by th3bucch** [comment]
Hi, latest update (1.1.0) brought back the issue.
Hope it will be fixed again, if not a problem.

Thanks

**Comment by Sean-StarLabs** [comment]
Fixed (again) in 1.1.2. It's just building now so should be available in an hour or so :)
