### ISSUE TITLE
[Question] Is this theme based on Adwaita?

### ISSUE THREAD

**Issue by Valleriite** [StarLabsLtd/StarLabsTheme#18]

**Comment by Sean-StarLabs** [comment]
No, it's largely based on Materia

**Comment by Valleriite** [comment]
> No, it's largely based on Materia

I think Materia is based on Adwaita

**Comment by Sean-StarLabs** [comment]
It is indeed.

**Comment by Valleriite** [comment]
What about the state changes requirement in gpl,
is that met in here?

**Comment by Sean-StarLabs** [comment]
Yup

**Comment by Valleriite** [comment]
> Yup

Nice,is there a file containing statement about the changes or what?
