### ISSUE TITLE
Fail to build Fedora

### ISSUE THREAD

**Issue by dbasinge** [StarLabsLtd/StarLabsTheme#2]
Getting the following errors with ninja -C build
ninja: Entering directory `build'
[1/5] Generating standard-gnome-shell with a custom command.
FAILED: gnome-shell/Standard/gnome-shell.css 
/usr/bin/sassc -a ../gnome-shell/Standard/gnome-shell.scss gnome-shell/Standard/gnome-shell.css
Error: File to import not found or unreadable: sections/scrollbars.
        on line 30 of ../gnome-shell/Standard/sass/_sections.scss
        from line 5 of ../gnome-shell/Standard/gnome-shell.scss
>> @import 'sections/scrollbars';				

   ^
[2/5] Generating light-gnome-shell with a custom command.
FAILED: gnome-shell/Light/gnome-shell.css 
/usr/bin/sassc -a ../gnome-shell/Light/gnome-shell.scss gnome-shell/Light/gnome-shell.css
Error: File to import not found or unreadable: sections/scrollbars.
        on line 30 of ../gnome-shell/Light/sass/_sections.scss
        from line 5 of ../gnome-shell/Light/gnome-shell.scss
>> @import 'sections/scrollbars';				

   ^
[5/5] Generating generate_gtk with a custom command.
ninja: build stopped: subcommand failed.

**Comment by dbasinge** [comment]
Output for meson build             
The Meson build system
Version: 0.49.2
Source dir: /home/homedir/devel/StarLabsTheme
Build dir: /home/homedir/devel/StarLabsTheme/build
Build type: native build
Project name: StarLabs
Project version: 0.1
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program sassc found: YES (/usr/bin/sassc)
Program sassc found: YES (/usr/bin/sassc)
Configuring index.theme using configuration
Program sassc found: YES (/usr/bin/sassc)
Configuring index.theme using configuration
Program sassc found: YES (/usr/bin/sassc)
Program sh found: YES (/usr/bin/sh)
Configuring cursor.theme using configuration
Configuring index.theme using configuration
Program meson/post_install.py found: YES (/home/homedir/devel/StarLabsTheme/icons/meson/post_install.py)
Program meson/plymouth found: YES (/home/homedir/devel/StarLabsTheme/plymouth/meson/plymouth)
Configuring starlabs.json using configuration
Configuring StarLabs.desktop using configuration
Configuring StarLabs-wayland.desktop using configuration
Configuring 99_StarLabs.gschema.override using configuration
Program meson/install-dock-override found: YES (/home/homedir/devel/StarLabsTheme/sessions/meson/install-dock-override)
Program meson/compile-schemas found: YES (/home/homedir/devel/StarLabsTheme/sessions/meson/compile-schemas)
Configuring index.theme using configuration
Build targets in project: 5
Found ninja-1.8.2 at /usr/bin/ninja

**Comment by Sean-StarLabs** [comment]
@dbasinge Should be fixed now, let me know if not.
