### ISSUE TITLE
update-alternatives warning

### ISSUE THREAD

**Issue by hailwood** [StarLabsLtd/StarLabsTheme#3]
When installing from the PPA I noticed this warning,
Is it something we need to be concerned with?

> update-alternatives: warning: skip creation of /usr/share/plymouth/themes/default.grub because associated file /usr/share/plymouth/themes/StarLabs/StarLabs.grub (of link group default.plymouth) doesn't exist

**Comment by Sean-StarLabs** [comment]
Thanks for reporting.

Nothing to worry about and we have a fix, will roll it out in the next version.
