### ISSUE TITLE
Failed to remove splash screen after uninstall

### ISSUE THREAD

**Issue by korjusk** [StarLabsLtd/StarLabsTheme#5]
Hello

I tried a lot of different ways to uninstall (including the instruction in this repo readme.md) this theme and all the related files but still after I reboot I see the StarLabs splash screen.
How can I remove it?

Picture of the splash screen: 
https://photos.google.com/share/AF1QipNlY4ZD7oMEtqKoDfB7TAGJhO0dI9FCUw06ecSdKpnlAqT4BuHLV6VhLiwZ9gSC4g/photo/AF1QipNtX1x1HL2o9jW2ztDDNmr2ic7oohSQ2EnAX9xN?key=enZDM05BNDI3bE52emVRRm4tb2h3aTQta3ZnSUJB

Thank you!

Edit: Ubuntu 18.04.2 and GNOME Shell 3.28.3

**Comment by Sean-StarLabs** [comment]
Hello

Did you install it from the PPA? 

What different ways to you try to uninstall?

**Comment by korjusk** [comment]
Installed:
```
sudo add-apt-repository ppa:starlabs/beta
sudo apt update
sudo apt install starlabstheme
```

Activated it in 'Tweaks' -> 'Appearance' -> 'Themes'

Deactivated by selecting different theme.

Uninstalled:
```
sudo apt remove starlabstheme
sudo update-alternatives --remove gdm3.css /usr/share/gnome-shell/theme/StarLabs/gnome-shell.css
sudo glib-compile-schemas /usr/share/glib-2.0/schemas 
sudo update-alternatives --remove default.plymouth /usr/share/plymouth/themes/starlabs-logo/starlabs-logo.plymouth
sudo update-initramfs -u
```

And removed all the files I found
```
locate starlab
rm ...
```

Updated 'locate'
```
sudo updatedb
locate starlab
```

And found no files.
```
sudo reboot
```

And its still there.

**Comment by Sean-StarLabs** [comment]
Run:
`sudo apt remove starlabstheme-*`

It probably won't work as the "locate starlab + rm ..." has probably broken the packages so if it fails, use the below: 

```
sudo update-alternatives --remove default.plymouth /usr/share/plymouth/themes/StarLabs/StarLabs.plymouth
sudo update-initramfs -u
```

**Comment by korjusk** [comment]
This removed stuff with warnings
```
sudo apt remove starlabstheme-*
```

```
sudo update-alternatives --remove default.plymouth /usr/share/plymouth/themes/StarLabs/StarLabs.plymouth
sudo update-initramfs -u
```
returned:
```
update-initramfs: Generating /boot/initrd.img-4.15.0-46-generic
```

but the logo is still there.

**Comment by Sean-StarLabs** [comment]
When you ran this:
`sudo update-alternatives --remove default.plymouth /usr/share/plymouth/themes/StarLabs/StarLabs.plymouth`

Did you see this:
`update-alternatives: using /usr/share/plymouth/themes/ubuntu-logo/ubuntu-logo.plymouth to provide /usr/share/plymouth/themes/default.plymouth (default.plymouth) in auto mode
`
?

**Comment by korjusk** [comment]
No. Nothing was returned after that command.

**Comment by Sean-StarLabs** [comment]
Can you try it again? Its one line and best to copy and paste.

**Comment by korjusk** [comment]
Did it, nothing was returned.

**Comment by Sean-StarLabs** [comment]
Let me know what this returns:
`sudo update-alternatives  --list default.plymouth`

**Comment by korjusk** [comment]
```
$ sudo update-alternatives --list default.plymouth
/usr/share/plymouth/themes/spinner/spinner.plymouth
/usr/share/plymouth/themes/ubuntu-logo/ubuntu-logo.plymouth
```

**Comment by Sean-StarLabs** [comment]
Okay, it's not Plymouth then. 

Only other place that splash screen is in is grub so can you let me know what this returns:
`ls /boot/grub`

**Comment by korjusk** [comment]
After that I don't have that splash screen anymore
```
$ ls /boot/grub
fonts             grub.cfg  i386-pc  unicode.pf2
gfxblacklist.txt  grubenv   locale   wallpaper.png
$ sudo remove /boot/grub/wallpaper.png
$ sudo reboot
```

Thank you for your help and fast replies! :)

I don't know if it's helpful but the grub.cfg file contained these lines:
```
...
if background_image /boot/grub/wallpaper.png; then
  true
else
  set menu_color_normal=white/black
  set menu_color_highlight=black/light-gray
fi
### END /etc/grub.d/05_debian_theme ###
...
### BEGIN /etc/grub.d/47_starlabs ###
set menu_color_normal=white/black
set menu_color_highlight=light-blue/white
set color_normal=white/black
### END /etc/grub.d/47_starlabs ###
```

**Comment by Sean-StarLabs** [comment]
Glad to hear.

It does, I'll do some testing now to get this fixed.

Thanks for trying the theme :)
