### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by algent-al** [StarLabsLtd/StarLabsTheme#6]
Tried this Theme on Manjaro Budgie, to see how it will look.
For windows i noticed too much transparency, missing icons for Budgie Desktop Settins items.
Overall cool icons, wallpapers, and cursor was nice too.
In the end i decided to uninstall but the uninstall command didn't work.
I run inside the folder from where I installed this theme: $ sudo ninja -C build uninstall
But it didn't work, so I had to use Timeshift.

**Comment by Sean-StarLabs** [comment]
Hi algent-al 

We haven't done any tested with Budgie yet but when we do, we will add the missing icons.

When you say "it didn't work", what did it do (or not do)?

**Comment by algent-al** [comment]
When you say "it didn't work", what did it do (or not do)?
- It didn't uninstall ($ sudo ninja -C build uninstall). This comand line didn't work.

I know it is not supposed to work on Budgie. Budgie is a Gnome derivative so i thought to try it.

**Comment by Sean-StarLabs** [comment]
How did it not work? Did you get any errors?

**Comment by algent-al** [comment]
Yes I got an error but didn't save the output.

Just tried again, but this time on Virtual Box.
![Starlabs Budgie](https://user-images.githubusercontent.com/46356616/54920279-2376df80-4f03-11e9-8d33-427ab36413ed.png)
![Starlabs Dark Budgie](https://user-images.githubusercontent.com/46356616/54920309-3689af80-4f03-11e9-9b9d-93e3e34f4636.png)
And this time uninstallation was succesful.
![Starlabs Uninstall](https://user-images.githubusercontent.com/46356616/54920350-47d2bc00-4f03-11e9-86ad-aa10e1a5a660.png)
Seems that i have done something wrong on my other PC.
