### ISSUE TITLE
Arch package preparations

### ISSUE THREAD

**Issue by yochananmarqos** [StarLabsLtd/StarLabsTheme#9]
I'm preparing an Arch PKGBUILD to add to the AUR and can't seem to find dependencies listed anywhere. They're missing from the Debian control files.

**Comment by Sean-StarLabs** [comment]
Awesome. We didn't add any dependencies so it could be installed without being forced to install a different desktop environment but if you wanted to add them, they would be:
```
gnome-shell
gdm3
plymouth
grub2-common
```

**Comment by yochananmarqos** [comment]
I see. I created a split package so most components can be installed separately if desired. It's live in the AUR: [`starlabstheme-git`](https://aur.archlinux.org/pkgbase/starlabstheme-git/).

**Comment by Sean-StarLabs** [comment]
Awesome. Thanks for doing this :)
